/**
 * `BymaxCacheModule` — the public NestJS dynamic module.
 *
 * Layer: server. Phase 1 surface: synchronous `forRoot()` wiring the
 * `ConnectionManager`, `KeyBuilder`, and DI tokens. The async `forRootAsync()`
 * lands in Phase 4 (CACHE-040); the inherited builder method is not yet wired
 * with the cache providers and must not be used until then.
 *
 * @see `docs/technical_specification.md` §2.1, §4 — Dynamic Module Pattern
 */
import { Module } from '@nestjs/common'
import type { DynamicModule, Provider } from '@nestjs/common'

import {
  BYMAX_CACHE_EVENTS,
  BYMAX_CACHE_KEY_BUILDER,
  BYMAX_CACHE_OPTIONS
} from './bymax-cache.constants'
import {
  ASYNC_OPTIONS_TYPE,
  ConfigurableModuleClass,
  MODULE_OPTIONS_TOKEN,
  OPTIONS_TYPE
} from './bymax-cache.module.builder'
import { applyDefaults, validateOptions } from './config/default-options'
import { ConnectionManager } from './connection/connection.manager'
import { KeyBuilder } from './utils/key-builder'

@Module({})
export class BymaxCacheModule extends ConfigurableModuleClass {
  /**
   * Registers the cache module synchronously.
   *
   * @param options - Consumer options; validated and defaulted at registration.
   * @returns The configured {@link DynamicModule}.
   * @throws {import('./errors/cache.exception').CacheException} When the options
   *   fail bootstrap validation (e.g. missing connection, misconfigured mode).
   */
  static override forRoot(options: typeof OPTIONS_TYPE): DynamicModule {
    validateOptions(options)
    const resolved = applyDefaults(options)

    const providers: Provider[] = [
      { provide: MODULE_OPTIONS_TOKEN, useValue: options },
      { provide: BYMAX_CACHE_OPTIONS, useValue: resolved },
      { provide: BYMAX_CACHE_EVENTS, useValue: resolved.events ?? null },
      ConnectionManager,
      KeyBuilder,
      { provide: BYMAX_CACHE_KEY_BUILDER, useExisting: KeyBuilder }
    ]

    return {
      module: BymaxCacheModule,
      global: resolved.isGlobal,
      providers,
      exports: [BYMAX_CACHE_OPTIONS, BYMAX_CACHE_KEY_BUILDER, ConnectionManager, KeyBuilder]
    }
  }

  /**
   * Rejects asynchronous registration until it is implemented in Phase 4.
   *
   * @remarks
   * The `forRootAsync` generated by {@link ConfigurableModuleClass} would build
   * a module missing the {@link ConnectionManager} and {@link KeyBuilder}
   * providers, silently producing a broken module. Failing loud here prevents
   * that until the real implementation lands (Phase 4 / CACHE-040).
   * @param _options - The asynchronous cache module options (ignored).
   * @returns Never returns; the method always throws.
   * @throws {Error} Always, signalling async registration is not yet available.
   */
  static override forRootAsync(_options: typeof ASYNC_OPTIONS_TYPE): DynamicModule {
    throw new Error(
      'BymaxCacheModule.forRootAsync is not available until Phase 4 — use forRoot for synchronous registration.'
    )
  }
}
