/**
 * `BymaxCacheModule` — the public NestJS dynamic module.
 *
 * Layer: server. Synchronous `forRoot()` wires the full Phase 1–3 surface:
 * `ConnectionManager`, `KeyBuilder`, `CacheService`, `PubSubService`,
 * `ScriptManagerService`, the default serializer, and the DI tokens. The shared
 * provider/export lists are factored into {@link BymaxCacheModule.buildCommonProviders}
 * / {@link BymaxCacheModule.buildCommonExports} so the async `forRootAsync()`
 * (Phase 4 / CACHE-040) can reuse them; until then the inherited builder method
 * is overridden to fail loud.
 *
 * @see `docs/technical_specification.md` §2.1, §4 — Dynamic Module Pattern
 */
import { Module } from '@nestjs/common'
import type { DynamicModule, Provider } from '@nestjs/common'

import {
  BYMAX_CACHE_EVENTS,
  BYMAX_CACHE_KEY_BUILDER,
  BYMAX_CACHE_OPTIONS,
  BYMAX_CACHE_SCRIPT_REGISTRY,
  BYMAX_CACHE_SERIALIZER
} from './bymax-cache.constants'
import {
  ASYNC_OPTIONS_TYPE,
  ConfigurableModuleClass,
  MODULE_OPTIONS_TOKEN,
  OPTIONS_TYPE
} from './bymax-cache.module.builder'
import { applyDefaults, validateOptions } from './config/default-options'
import type { ResolvedOptions } from './config/resolved-options'
import { ConnectionManager } from './connection/connection.manager'
import { CacheService } from './services/cache.service'
import { PubSubService } from './services/pubsub.service'
import { ScriptManagerService } from './services/script-manager.service'
import { JsonSerializer } from './utils/json-serializer'
import { KeyBuilder } from './utils/key-builder'

@Module({})
export class BymaxCacheModule extends ConfigurableModuleClass {
  /**
   * Registers the cache module synchronously.
   *
   * @param options - Consumer options; validated and defaulted at registration.
   * @returns The configured {@link DynamicModule}.
   * @throws {import('./errors/cache.exception').CacheException} When the options
   *   fail bootstrap validation (e.g. missing connection, misconfigured mode).
   */
  static override forRoot(options: typeof OPTIONS_TYPE): DynamicModule {
    validateOptions(options)
    const resolved = applyDefaults(options)

    const providers: Provider[] = [
      { provide: MODULE_OPTIONS_TOKEN, useValue: options },
      { provide: BYMAX_CACHE_OPTIONS, useValue: resolved },
      { provide: BYMAX_CACHE_EVENTS, useValue: resolved.events ?? null },
      ...BymaxCacheModule.buildCommonProviders(resolved)
    ]

    return {
      module: BymaxCacheModule,
      global: resolved.isGlobal,
      providers,
      exports: BymaxCacheModule.buildCommonExports()
    }
  }

  /**
   * Rejects asynchronous registration until it is implemented in Phase 4.
   *
   * @remarks
   * The `forRootAsync` generated by {@link ConfigurableModuleClass} would build
   * a module missing the {@link ConnectionManager} and {@link KeyBuilder}
   * providers, silently producing a broken module. Failing loud here prevents
   * that until the real implementation lands (Phase 4 / CACHE-040).
   * @param _options - The asynchronous cache module options (ignored).
   * @returns Never returns; the method always throws.
   * @throws {Error} Always, signalling async registration is not yet available.
   */
  static override forRootAsync(_options: typeof ASYNC_OPTIONS_TYPE): DynamicModule {
    throw new Error(
      'BymaxCacheModule.forRootAsync is not available until Phase 4 — use forRoot for synchronous registration.'
    )
  }

  /**
   * Providers shared by `forRoot` (and `forRootAsync` in Phase 4). The serializer
   * provider honors a consumer-supplied serializer (`useValue`) so anything
   * injecting `BYMAX_CACHE_SERIALIZER` receives the configured instance, and
   * otherwise falls back to the default {@link JsonSerializer} class.
   *
   * @param resolved - Resolved options; needed for the conditional serializer.
   * @returns The common provider list.
   */
  private static buildCommonProviders(resolved: ResolvedOptions): Provider[] {
    return [
      resolved.serializer
        ? { provide: BYMAX_CACHE_SERIALIZER, useValue: resolved.serializer }
        : { provide: BYMAX_CACHE_SERIALIZER, useClass: JsonSerializer },
      ConnectionManager,
      KeyBuilder,
      CacheService,
      PubSubService,
      ScriptManagerService,
      { provide: BYMAX_CACHE_KEY_BUILDER, useExisting: KeyBuilder },
      { provide: BYMAX_CACHE_SCRIPT_REGISTRY, useExisting: ScriptManagerService }
    ]
  }

  /**
   * Tokens and services exported by `forRoot` (and `forRootAsync` in Phase 4).
   *
   * @returns The common export list.
   */
  private static buildCommonExports(): NonNullable<DynamicModule['exports']> {
    return [
      BYMAX_CACHE_OPTIONS,
      BYMAX_CACHE_KEY_BUILDER,
      BYMAX_CACHE_SCRIPT_REGISTRY,
      BYMAX_CACHE_SERIALIZER,
      ConnectionManager,
      KeyBuilder,
      CacheService,
      PubSubService,
      ScriptManagerService
    ]
  }
}
